### ISSUE TITLE
Rounding issues with get_item_tax_amount

### ISSUE THREAD

**Issue by juhosyrj** [krokedil/woocommerce-gateway-klarna#89] opened 2017-07-12 12:34 UTC
### Expected behavior
Tax_rate is correct in both ends (Woocommerce & Klarna)
-

### Actual behavior
Tax_rate is incorrect at Klarna's end due to rounding error.

Product details from Klarna's logs:
          {
            "discount_rate": 0,
            "name": "Testituote ALV-test",
            "quantity": 1,
            "reference": "1",
            "tax_rate": 2407,
            "total_price_excluding_tax": 403,
            "total_price_including_tax": 500,
            "total_tax_amount": 97,
            "type": "physical",
            "unit_price": 500
          }

The line that produces rounding errors:
$item_tax_rate = round( $cart_item['line_subtotal_tax'] / $cart_item['line_subtotal'] * 100 * 100 );

e.g.
round( 500 / 403 * 100 * 100 ) == 2407

-

### Steps to reproduce the behavior
Buy a product
Product price: €5.00
Tax% / VAT: 24.0000

Add product the cart, go to checkout, check tax_rate from logs.
-

### Klarna plugin version
I tested with 2.3.6, but happens with other versions as well.
-

### WordPress version
4.7.5
-

### WooCommerce version
3.0.7
-

### Klarna country
Finland
-

**Comment by slobodan** [comment] 2017-07-19 09:08
@juhosyrj this is something I have run into recently and from what I see it is caused by WooCommerce rounding. Our plugin is reading prices including tax, prices excluding tax and tax amount from WooCommerce cart directly and what's returned in the example you mentioned is:

* `4.03` for price excluding tax
* `0.97` for tax amount

We then use those two to calculate tax rate and send it to Klarna as well.

The amounts really should be `4.0322580645` for price excluding tax and `96.7741935484` for tax amount.

Applying the formula from your comment, which is correct way to calculate tax rate, we get `2406.9478908189` before rounding (percentage multiplied by 100 is sent to Klarna), but it's not because of our calculation, it's because of the formula being fed wrong values by WooCommerce.

And to make things more mysterious, inside WC_Cart object values like cart_contents_total, tax_total etc. are rounded to three decimal places, while individual cart items are rounded to two. Changing `Number of decimals` setting does not seem to affect this.

From what I see this is a known issue in WooCommerce:

* Issue where this was first reported: https://github.com/woocommerce/woocommerce/issues/14458
* Pull request where most of the discussion is happening: https://github.com/woocommerce/woocommerce/pull/14475

Looks like that PR is not getting merged anytime soon though.

I hope I'm wrong and a six year old platform does not have this issue, but everything points to it being so. Other than wait for WooCommerce to fix this, I don't know what we can do. We could round tax rate to integer in our plugin before sending it to Klarna, but that could cause two issues:

* Klarna not accepting that item because of the mismatch - not very likely because Klarna does allow small mismatches, but could happen
* Our plugin rounding tax rate to what is actually wrong amount when no rounding is needed - this one would be more likely

This comment says entering prices exclusive of tax should help the rounding issue, I haven't tested this myself, but it's worth exploring.

**Comment by slobodan** [comment] 2017-07-19 09:21
One possible way to solve this is to use `wc_get_price_decimals` filter, from `wc_get_price_decimals()` in `wc-formatting-functions.php`, and increase number of decimal places used in calculations.

However, this would also affect displayed prices in store's frontend.

**Comment by slobodan** [comment] 2017-07-19 10:21
Update: Increasing number of decimals (in Aelia currency switcher page, for each currency, if you use Aelia) does solve the rounding issue, but it then shows prices with more decimals in front-end as well.

**Comment by juhosyrj** [comment] 2017-07-21 08:42
Thanks for detailed answer!

**Comment by juhosyrj** [comment] 2017-08-22 07:41
Changing the rounding a bit, from:
$item_tax_rate = round( $cart_item['line_subtotal_tax'] / $cart_item['line_subtotal'] * 100 * 100 );

To:
$item_tax_rate = round( $cart_item['line_subtotal_tax'] / $cart_item['line_subtotal'] * 100 ) * 100;

...has resolved the VAT issue for couple of Finnish merchants. We haven't noticed any side effects yet.

**Comment by slobodan** [comment] 2017-08-22 07:54
@juhosyrj thanks for helping with this.

I'd be hesitant to add a setting, because it would be an overkill, and like you said the setting would actually make the value wrong for xy.zw values.

However, you can use `klarna_process_cart_contents` filter now:

https://github.com/krokedil/woocommerce-gateway-klarna/blob/master/classes/class-wc-to-klarna.php#L300

To round tax rates to integer values. Would that be sufficient?

**Comment by slobodan** [comment] 2017-08-29 09:56
@juhosyrj could you try this branch, hopefully it fixes the tax rate rounding issue once and for all:

https://github.com/krokedil/woocommerce-gateway-klarna/tree/feature/tax-rate-rounding

It reads the rate in a different way, using WC_Tax class, versus calculating it from cart totals.

**Closed** 2017-09-06 06:49 UTC
