### ISSUE TITLE
Klarna shows decimals for payment amount even when it is disabled in WooCommerce

### ISSUE THREAD

**Issue by spraveenitpro** [krokedil/woocommerce-gateway-klarna#88] opened 2017-07-07 11:16 UTC
### Expected behavior

No decimals in the amount to be paid with Klarna.

### Actual behavior

Shown 2 decimals in the amount to be paid with Klarna.

### Steps to reproduce the behavior

1. Here is my settings page: ![](http://cld.wthms.co/jGCzqm+)
2. Here is my tax settings for sweden:  ![](http://cld.wthms.co/pgcYn4+)
3. On the cart page we are show that we have to pay 186Kr with out any decimals ![](http://cld.wthms.co/o3Tja+)
4. On the Klarna Checkout page however we are shown with 2 decimals ![](http://cld.wthms.co/e14Iep+)
### Klarna plugin version

2.3.11
### WordPress version

4.8
### WooCommerce version

3.1

### Klarna country

Sweden

### Ticket

zd-woothemes-598241  @NiklasHogefjord @Victor-Krokedil

**Comment by NiklasHogefjord** [comment] 2017-07-07 15:27
This is not a bug in the payment gateway. It's not possible to use 0 decimals when using the Klarna payment gateway. The merchant needs to use 2 decimals. We will update the documentation with info about this.

Klarna wants all order lines to be sent to them when creating an order. The order lines must be specified with the price and tax rate. When changing the decimal display setting to 0 in WooCommerce the store is actually calculating tax and net price wrong (since it rounds up/down to the closest integer). We have written an article about this here: https://krokedil.com/dont-display-prices-with-0-decimals-in-woocommerce/.

I'm closing this issue.

**Closed by NiklasHogefjord** 2017-07-07 15:27 UTC
